dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

install:
  - yarn

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a yarn test --single-run --no-progress --browser=ChromeNoSandbox

before_deploy:
  - yarn build

deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  token:
    secure: "oZKY0XdJaRnWb0OcjNmS6cUrGI7bpr2IPcsfjX1B66h7Zo6ENbQDzIS/TAV/uVd7Wv/pisI1FPgaFOmaGqU6mMjLYxpNkzGZ0IoqTQh1K/SdCW8eksDnYNuermlv68Qu87wp9JH4C5a9BykpquKs0J3bGza/I8HlGE3XzXnMCMgVqq70fwuJeKhBmX8QuXof9Vcg8yGsshd7B66zJI0RzGW75VXmoypeEtmmw9/m4T/m3XlwUop72+C+YNfwlfyCRAc6YgCca8xXlA5M2ob2szdJl8sSQk7aF+1eBiZvourBa3Pk6e8opOISUUsQgnUnxfjEAaw0B8OmYtFgZTufNH9rZA+6xRpQJnd5JlKWsYxJ8blToCABmftxMdOetLxfQKoMq2ajq9w+UGHCgzO4u2mqIChj0V99mWkWDT1nO9t2A7DD9uXsuajiVNE/fra+fGTqhJdDGkhvEnUXtaObECqoF/SMxPMxPjPtNGsy93m6j7JMbfHm/tjIStOxpPU2dNtMI3x03C6RmlAzxGxXyeFQ4Nt8EI2NVvzyvHaOGlJ/RrZ0tT+CPtnSXF0K+gazPjegA61XdjUw7gnKmRDTikKB9g8B2vKHQptWxD5d0OFzIJyL4fH9I9UYNVn+xpNW8OchLiqT6eqrEsIU+BciPcLJkGVBzZjbcTHz3NWCttU="
